name:                icfpc2025
version:             0.1.0.0
github:              TeamSampou/icfpc2025
license:             BSD3
author:              Team Sampou
maintainer:          nobsun@sampou.org
copyright:           © 2025, Team Sampou

extra-doc-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Experiment

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/TeamSampou/icfpc2025#readme>

flags:
  doctests:
    manual: true
    default: false

dependencies:
- base >= 4.7 && < 5
- bytestring
- time
- array
- containers
- mtl
- text
- directory
- exceptions
- filepath
- process
- stm

language: GHC2024

default-extensions:
- ImplicitParams
- ImportQualifiedPost
- LambdaCase
- MultiWayIf
- NPlusKPatterns
## - LexicalNegation
## - OverloadedStrings
## - DataKinds
## - PolyKinds
## - NoStarIsType
## - TypeFamilyDependencies
## - UndecidableInstances
## - CPP

ghc-options:
- -Wall
- -Wno-unticked-promoted-constructors
- -Wno-unused-imports
- -Wno-unused-top-binds
- -Wno-orphans

library:
  dependencies:
  - aeson
  - dotenv
  - http-conduit
  - split
  ## - constraints
  ## - extra
  ## - fgl
  ## - fgl-visualize
  ## - free
  ## - gloss
  ## - hmatrix
  ## - recursion-schemes
  ## - vector
  ## - prettyprinter
  source-dirs: src

executables:
  icfpc2025:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -rtsopts
    dependencies:
    - icfpc2025

  add-entry:
    main:                 Main.hs
    source-dirs:          app/zzz/add-entry
    ghc-options:
    - -rtsopts
    dependencies:
    - icfpc2025

  oga-solve1:
    main:                 Main.hs
    source-dirs:          app/oga
    ghc-options:
    - -rtsopts
    dependencies:
    - icfpc2025

tests:
  icfpc2025-test:
    main:                spec.hs
    source-dirs:         test
    dependencies:
    - icfpc2025
    - utf8-string
    - unicode-show
    - hspec
    - main-tester

  icfpc2025-doctest:
    when:
    - condition: flag(doctests)
      then:
        buildable: true
      else:
        buildable: false
    main:                doctests.hs
    source-dirs:         test
    other-modules:       []
    dependencies:
    - icfpc2025
    - doctest
